config/routes.rb
Rails.application.routes.draw do
  resources :dis_doseunits
  resources :dis_doseform_route_maps
  resources :dis_generic_hepatic_imps
  resources :dis_duplicate_therapies
  resources :dis_doseform_doseunit_links
  resources :dis_dispensable_generics
  resources :dis_vaccine_types
  resources :dis_additive_frequencies
  resources :dis_doseperiods
  resources :dis_doseperiods
  resources :dis_drug_drug_interactions
  resources :dis_routed_doseform_generics
  resources :dis_doseunit_convertions
  resources :dis_generic_alcohol_interactions
  resources :dis_nfi_schedules
  resources :dis_generic_lactations
  resources :dis_generic_monographs
  resources :dis_generic_contraceptive_interactions
  resources :dis_alcohol_interactions
  resources :dis_datasources
  resources :dis_brandnames
  resources :dis_doseforms
  resources :dis_durations
  resources :dis_foodintakes
  resources :dis_generics
  resources :dis_generic_indications
  resources :dis_indiastates
  resources :dis_indications
  resources :dis_ingredients
  resources :dis_manufacturers
  resources :dis_packagetypes
  resources :dis_pregnancy_categories
  resources :dis_routes
  resources :dis_routed_generics
  resources :dis_statuses
  resources :dis_systems
  resources :dis_therapueticgroups
  namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
     resources :combination_doses
     resources :combination_contents
     resources :dis_generics
     resources :dis_additive_frequencies
     resources :dis_alcohol_interactions
     resources :dis_brandnames
     resources :dis_datasources
     resources :dis_dispensable_generics
     resources :dis_doseform_doseunit_links
     resources :dis_doseform_route_maps
     resources :dis_doseforms
     resources :dis_doseperiods
     resources :dis_doseunit_convertions
     resources :dis_doseunits
     resources :dis_drug_drug_interactions
     resources :dis_duplicate_therapies
     resources :dis_durations
     resources :dis_foodintakes
     resources :dis_generic_alcohol_interactions
     resources :dis_generic_contraceptive_interactions
     resources :dis_generic_hepatic_imps
     resources :dis_generic_indications
     resources :dis_generic_lactations
     resources :dis_generic_monographs
     resources :dis_indiastates
     resources :dis_indications
     resources :dis_ingredients
     resources :dis_manufacturers
     resources :dis_nfi_schedules
     resources :dis_packagetypes
     resources :dis_pregnancy_categories
     resources :dis_routed_doseform_generics
     resources :dis_routed_generics
     resources :dis_routes
     resources :dis_statuses
     resources :dis_systems
     resources :dis_therapueticgroups
     resources :dis_vaccine_types
     get '/search', to: 'dis_generics#search', as: 'search'
   end
 end
  resources :combination_doses
  resources :combination_contents
  resources :tests
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'
  root 'static_pages#home'

end

app/models/dis_therapueticgroup.rb
class DisTherapueticgroup < ActiveRecord::Base
end

app/controllers/api/v1/dis_therapueticgroups_controller.rb
module Api
  module V1
class DisTherapueticgroupsController < ApplicationController
  before_action :set_therapueticgroup, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  respond_to :json
  # GET /therapueticgroups
  # GET /therapueticgroups.json
  def index
  # @cd = DisTherapueticgroup.all
    c = DisTherapueticgroup.paginate(:page => params[:page], :per_page => 10)
    e = c.count
    c = c.as_json
    d = [{"Count" => e}]
    m = {"a" => c ,"b" => d}
    #  n = c.to_a << @m
    respond_with m
  end

  # GET /therapueticgroups/1
  # GET /therapueticgroups/1.json
  def show
     respond_with DisTherapueticgroup.find(params[:id])
  end

  # GET /therapueticgroups/new
  def new
    @therapueticgroup = DisTherapueticgroup.new
  end

  # GET /therapueticgroups/1/edit
  def edit
  end

  # POST /therapueticgroups
  # POST /therapueticgroups.json
  def create
    @therapueticgroup = DisTherapueticgroup.new(therapueticgroup_params)


      if @therapueticgroup.save
        flash[:notice] = "Task was successfully created."
         respond_with(@therapueticgroup)
       else
         flash[:notice] = "Task was not created."
       end
  end

  # PATCH/PUT /therapueticgroups/1
  # PATCH/PUT /therapueticgroups/1.json
  def update
    respond_to do |format|
      if @therapueticgroup.update(therapueticgroup_params)
        format.html { redirect_to @therapueticgroup, notice: 'Combination dose was successfully updated.' }
        format.json { render :show, status: :ok, location: @therapueticgroup }
      else
        format.html { render :edit }
        format.json { render json: @therapueticgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /therapueticgroups/1
  # DELETE /therapueticgroups/1.json
  def destroy
    @therapueticgroup.destroy
    respond_to do |format|
      format.html { redirect_to therapueticgroups_url, notice: 'Combination dose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_therapueticgroup
      @therapueticgroup = DisTherapueticgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def therapueticgroup_params
      params.require(:therapueticgroup).permit(:name, :system_id, :status_id)
    end
end
 end
 end

app/controllers/dis_therapueticgroups_controller.rb
class DisTherapueticgroupsController < ApplicationController
  before_action :set_dis_therapueticgroup, only: [:show, :edit, :update, :destroy]

  # GET /dis_therapueticgroups
  # GET /dis_therapueticgroups.json
  def index
    @dis_therapueticgroups = DisTherapueticgroup.all
  end

  # GET /dis_therapueticgroups/1
  # GET /dis_therapueticgroups/1.json
  def show
  end

  # GET /dis_therapueticgroups/new
  def new
    @dis_therapueticgroup = DisTherapueticgroup.new
  end

  # GET /dis_therapueticgroups/1/edit
  def edit
  end

  # POST /dis_therapueticgroups
  # POST /dis_therapueticgroups.json
  def create
    @dis_therapueticgroup = DisTherapueticgroup.new(dis_therapueticgroup_params)

    respond_to do |format|
      if @dis_therapueticgroup.save
        format.html { redirect_to @dis_therapueticgroup, notice: 'Dis therapueticgroup was successfully created.' }
        format.json { render :show, status: :created, location: @dis_therapueticgroup }
      else
        format.html { render :new }
        format.json { render json: @dis_therapueticgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dis_therapueticgroups/1
  # PATCH/PUT /dis_therapueticgroups/1.json
  def update
    respond_to do |format|
      if @dis_therapueticgroup.update(dis_therapueticgroup_params)
        format.html { redirect_to @dis_therapueticgroup, notice: 'Dis therapueticgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @dis_therapueticgroup }
      else
        format.html { render :edit }
        format.json { render json: @dis_therapueticgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dis_therapueticgroups/1
  # DELETE /dis_therapueticgroups/1.json
  def destroy
    @dis_therapueticgroup.destroy
    respond_to do |format|
      format.html { redirect_to dis_therapueticgroups_url, notice: 'Dis therapueticgroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dis_therapueticgroup
      @dis_therapueticgroup = DisTherapueticgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dis_therapueticgroup_params
      params.require(:dis_therapueticgroup).permit(:name, :system_id, :status_id)
    end
end

app/helpers/dis_therapueticgroups_helper.rb
module DisTherapueticgroupsHelper
end

app/views/dis_therapueticgroups/_form.html.erb
<%= simple_form_for(@dis_therapueticgroup) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :system_id %>
    <%= f.input :status_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save" %>
  </div>
<% end %>

app/views/dis_therapueticgroups/edit.html.erb
<h1>Editing Dis Therapueticgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @dis_therapueticgroup %> |
<%= link_to 'Back', dis_therapueticgroups_path %>

app/views/dis_therapueticgroups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dis Therapueticgroups</h1>

<table id="example" class="table table-bordered table-hover table-striped datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>System</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @dis_therapueticgroups.each do |dis_therapueticgroup| %>
      <tr>
        <td><%= dis_therapueticgroup.id %></td>
        <td><%= dis_therapueticgroup.name %></td>
        <td><%= dis_therapueticgroup.system_id %></td>
        <td><%= dis_therapueticgroup.status_id %></td>
        <td><%= link_to 'Show', dis_therapueticgroup %>,<%= link_to 'Edit', edit_dis_therapueticgroup_path(dis_therapueticgroup) %>,<%= link_to 'Destroy', dis_therapueticgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dis Therapueticgroup', new_dis_therapueticgroup_path %>

app/views/dis_therapueticgroups/new.html.erb
<h1>New Dis Therapueticgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', dis_therapueticgroups_path %>

app/views/dis_therapueticgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @dis_therapueticgroup.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dis_therapueticgroup.name %>
</p>

<p>
  <strong>System:</strong>
  <%= @dis_therapueticgroup.system_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dis_therapueticgroup.status_id %>
</p>

<%= link_to 'Edit', edit_dis_therapueticgroup_path(@dis_therapueticgroup) %> |
<%= link_to 'Back', dis_therapueticgroups_path %>