config/routes.rb
Rails.application.routes.draw do
  resources :dis_doseunits
  resources :dis_doseform_route_maps
  resources :dis_generic_hepatic_imps
  resources :dis_duplicate_therapies
  resources :dis_doseform_doseunit_links
  resources :dis_dispensable_generics
  resources :dis_vaccine_types
  resources :dis_additive_frequencies
  resources :dis_doseperiods
  resources :dis_doseperiods
  resources :dis_drug_drug_interactions
  resources :dis_routed_doseform_generics
  resources :dis_doseunit_convertions
  resources :dis_generic_alcohol_interactions
  resources :dis_nfi_schedules
  resources :dis_generic_lactations
  resources :dis_generic_monographs
  resources :dis_generic_contraceptive_interactions
  resources :dis_alcohol_interactions
  resources :dis_datasources
  resources :dis_brandnames
  resources :dis_doseforms
  resources :dis_durations
  resources :dis_foodintakes
  resources :dis_generics
  resources :dis_generic_indications
  resources :dis_indiastates
  resources :dis_indications
  resources :dis_ingredients
  resources :dis_manufacturers
  resources :dis_packagetypes
  resources :dis_pregnancy_categories
  resources :dis_routes
  resources :dis_routed_generics
  resources :dis_statuses
  resources :dis_systems
  resources :dis_therapueticgroups
  namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
     resources :combination_doses
     resources :combination_contents
     resources :dis_generics
     resources :dis_additive_frequencies
     resources :dis_alcohol_interactions
     resources :dis_brandnames
     resources :dis_datasources
     resources :dis_dispensable_generics
     resources :dis_doseform_doseunit_links
     resources :dis_doseform_route_maps
     resources :dis_doseforms
     resources :dis_doseperiods
     resources :dis_doseunit_convertions
     resources :dis_doseunits
     resources :dis_drug_drug_interactions
     resources :dis_duplicate_therapies
     resources :dis_durations
     resources :dis_foodintakes
     resources :dis_generic_alcohol_interactions
     resources :dis_generic_contraceptive_interactions
     resources :dis_generic_hepatic_imps
     resources :dis_generic_indications
     resources :dis_generic_lactations
     resources :dis_generic_monographs
     resources :dis_indiastates
     resources :dis_indications
     resources :dis_ingredients
     resources :dis_manufacturers
     resources :dis_nfi_schedules
     resources :dis_packagetypes
     resources :dis_pregnancy_categories
     resources :dis_routed_doseform_generics
     resources :dis_routed_generics
     resources :dis_routes
     resources :dis_statuses
     resources :dis_systems
     resources :dis_therapueticgroups
     resources :dis_vaccine_types
     get '/search', to: 'dis_generics#search', as: 'search'
   end
 end
  resources :combination_doses
  resources :combination_contents
  resources :tests
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'
  root 'static_pages#home'

end

app/controllers/api/v1/dis_generic_alcohol_interactions_controller.rb
module Api
  module V1
class DisGenericAlcoholInteractionsController < ApplicationController
  before_action :set_generic_alcohol_interaction, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  respond_to :json
  # GET /generic_alcohol_interactions
  # GET /generic_alcohol_interactions.json
  def index
  # @cd = DisGenericAlcoholInteraction.all
    c = DisGenericAlcoholInteraction.paginate(:page => params[:page], :per_page => 10)
    e = c.count
    c = c.as_json
    d = [{"Count" => e}]
    m = {"a" => c ,"b" => d}
    #  n = c.to_a << @m
    respond_with m
  end

  # GET /generic_alcohol_interactions/1
  # GET /generic_alcohol_interactions/1.json
  def show
     respond_with DisGenericAlcoholInteraction.find(params[:id])
  end

  # GET /generic_alcohol_interactions/new
  def new
    @generic_alcohol_interaction = DisGenericAlcoholInteraction.new
  end

  # GET /generic_alcohol_interactions/1/edit
  def edit
  end

  # POST /generic_alcohol_interactions
  # POST /generic_alcohol_interactions.json
  def create
    @generic_alcohol_interaction = DisGenericAlcoholInteraction.new(generic_alcohol_interaction_params)


      if @generic_alcohol_interaction.save
        flash[:notice] = "Task was successfully created."
         respond_with(@generic_alcohol_interaction)
       else
         flash[:notice] = "Task was not created."
       end
  end

  # PATCH/PUT /generic_alcohol_interactions/1
  # PATCH/PUT /generic_alcohol_interactions/1.json
  def update
    respond_to do |format|
      if @generic_alcohol_interaction.update(generic_alcohol_interaction_params)
        format.html { redirect_to @generic_alcohol_interaction, notice: 'Combination dose was successfully updated.' }
        format.json { render :show, status: :ok, location: @generic_alcohol_interaction }
      else
        format.html { render :edit }
        format.json { render json: @generic_alcohol_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generic_alcohol_interactions/1
  # DELETE /generic_alcohol_interactions/1.json
  def destroy
    @generic_alcohol_interaction.destroy
    respond_to do |format|
      format.html { redirect_to generic_alcohol_interactions_url, notice: 'Combination dose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generic_alcohol_interaction
      @generic_alcohol_interaction = DisGenericAlcoholInteraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generic_alcohol_interaction_params
      params.require(:generic_alcohol_interaction).permit(:generic_id, :alcohol_interaction_id, :status_id, :datasource_id)
    end
end
 end
 end

app/controllers/dis_generic_alcohol_interactions_controller.rb
class DisGenericAlcoholInteractionsController < ApplicationController
  before_action :set_dis_generic_alcohol_interaction, only: [:show, :edit, :update, :destroy]

  # GET /dis_generic_alcohol_interactions
  # GET /dis_generic_alcohol_interactions.json
  def index
    @dis_generic_alcohol_interactions = DisGenericAlcoholInteraction.all
  end

  # GET /dis_generic_alcohol_interactions/1
  # GET /dis_generic_alcohol_interactions/1.json
  def show
  end

  # GET /dis_generic_alcohol_interactions/new
  def new
    @dis_generic_alcohol_interaction = DisGenericAlcoholInteraction.new
  end

  # GET /dis_generic_alcohol_interactions/1/edit
  def edit
  end

  # POST /dis_generic_alcohol_interactions
  # POST /dis_generic_alcohol_interactions.json
  def create
    @dis_generic_alcohol_interaction = DisGenericAlcoholInteraction.new(dis_generic_alcohol_interaction_params)

    respond_to do |format|
      if @dis_generic_alcohol_interaction.save
        format.html { redirect_to @dis_generic_alcohol_interaction, notice: 'Dis generic alcohol interaction was successfully created.' }
        format.json { render :show, status: :created, location: @dis_generic_alcohol_interaction }
      else
        format.html { render :new }
        format.json { render json: @dis_generic_alcohol_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dis_generic_alcohol_interactions/1
  # PATCH/PUT /dis_generic_alcohol_interactions/1.json
  def update
    respond_to do |format|
      if @dis_generic_alcohol_interaction.update(dis_generic_alcohol_interaction_params)
        format.html { redirect_to @dis_generic_alcohol_interaction, notice: 'Dis generic alcohol interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @dis_generic_alcohol_interaction }
      else
        format.html { render :edit }
        format.json { render json: @dis_generic_alcohol_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dis_generic_alcohol_interactions/1
  # DELETE /dis_generic_alcohol_interactions/1.json
  def destroy
    @dis_generic_alcohol_interaction.destroy
    respond_to do |format|
      format.html { redirect_to dis_generic_alcohol_interactions_url, notice: 'Dis generic alcohol interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dis_generic_alcohol_interaction
      @dis_generic_alcohol_interaction = DisGenericAlcoholInteraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dis_generic_alcohol_interaction_params
      params.require(:dis_generic_alcohol_interaction).permit(:generic_id, :alcohol_interaction_id, :status_id, :datasource_id)
    end
end

app/helpers/dis_generic_alcohol_interactions_helper.rb
module DisGenericAlcoholInteractionsHelper
end

app/views/dis_generic_alcohol_interactions/_form.html.erb
<%= simple_form_for(@dis_generic_alcohol_interaction) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :generic_id %>
    <%= f.input :alcohol_interaction_id %>
    <%= f.input :status_id %>
    <%= f.input :datasource_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dis_generic_alcohol_interactions/edit.html.erb
<h1>Editing Dis Generic Alcohol Interaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @dis_generic_alcohol_interaction %> |
<%= link_to 'Back', dis_generic_alcohol_interactions_path %>

app/views/dis_generic_alcohol_interactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dis Generic Alcohol Interactions</h1>

<table id="example" class="table table-bordered table-hover table-striped datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Generic</th>
      <th>Alcohol interaction</th>
      <th>Status</th>
      <th>Datasource</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @dis_generic_alcohol_interactions.each do |dis_generic_alcohol_interaction| %>
      <tr>
        <td><%= dis_generic_alcohol_interaction.generic_id %></td>
        <td><%= dis_generic_alcohol_interaction.alcohol_interaction_id %></td>
        <td><%= dis_generic_alcohol_interaction.status_id %></td>
        <td><%= dis_generic_alcohol_interaction.datasource_id %></td>
        <td><%= link_to 'Show', dis_generic_alcohol_interaction %>,<%= link_to 'Edit', edit_dis_generic_alcohol_interaction_path(dis_generic_alcohol_interaction) %>,<%= link_to 'Destroy', dis_generic_alcohol_interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dis Generic Alcohol Interaction', new_dis_generic_alcohol_interaction_path %>

app/views/dis_generic_alcohol_interactions/new.html.erb
<h1>New Dis Generic Alcohol Interaction</h1>

<%= render 'form' %>

<%= link_to 'Back', dis_generic_alcohol_interactions_path %>

app/views/dis_generic_alcohol_interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Generic:</strong>
  <%= @dis_generic_alcohol_interaction.generic_id %>
</p>

<p>
  <strong>Alcohol interaction:</strong>
  <%= @dis_generic_alcohol_interaction.alcohol_interaction_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dis_generic_alcohol_interaction.status_id %>
</p>

<p>
  <strong>Datasource:</strong>
  <%= @dis_generic_alcohol_interaction.datasource_id %>
</p>

<%= link_to 'Edit', edit_dis_generic_alcohol_interaction_path(@dis_generic_alcohol_interaction) %> |
<%= link_to 'Back', dis_generic_alcohol_interactions_path %>