config/routes.rb
Rails.application.routes.draw do
  resources :dis_doseunits
  resources :dis_doseform_route_maps
  resources :dis_generic_hepatic_imps
  resources :dis_duplicate_therapies
  resources :dis_doseform_doseunit_links
  resources :dis_dispensable_generics
  resources :dis_vaccine_types
  resources :dis_additive_frequencies
  resources :dis_doseperiods
  resources :dis_doseperiods
  resources :dis_drug_drug_interactions
  resources :dis_routed_doseform_generics
  resources :dis_doseunit_convertions
  resources :dis_generic_alcohol_interactions
  resources :dis_nfi_schedules
  resources :dis_generic_lactations
  resources :dis_generic_monographs
  resources :dis_generic_contraceptive_interactions
  resources :dis_alcohol_interactions
  resources :dis_datasources
  resources :dis_brandnames
  resources :dis_doseforms
  resources :dis_durations
  resources :dis_foodintakes
  resources :dis_generics
  resources :dis_generic_indications
  resources :dis_indiastates
  resources :dis_indications
  resources :dis_ingredients
  resources :dis_manufacturers
  resources :dis_packagetypes
  resources :dis_pregnancy_categories
  resources :dis_routes
  resources :dis_routed_generics
  resources :dis_statuses
  resources :dis_systems
  resources :dis_therapueticgroups
  namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
     resources :combination_doses
     resources :combination_contents
     resources :dis_generics
     resources :dis_additive_frequencies
     resources :dis_alcohol_interactions
     resources :dis_brandnames
     resources :dis_datasources
     resources :dis_dispensable_generics
     resources :dis_doseform_doseunit_links
     resources :dis_doseform_route_maps
     resources :dis_doseforms
     resources :dis_doseperiods
     resources :dis_doseunit_convertions
     resources :dis_doseunits
     resources :dis_drug_drug_interactions
     resources :dis_duplicate_therapies
     resources :dis_durations
     resources :dis_foodintakes
     resources :dis_generic_alcohol_interactions
     resources :dis_generic_contraceptive_interactions
     resources :dis_generic_hepatic_imps
     resources :dis_generic_indications
     resources :dis_generic_lactations
     resources :dis_generic_monographs
     resources :dis_indiastates
     resources :dis_indications
     resources :dis_ingredients
     resources :dis_manufacturers
     resources :dis_nfi_schedules
     resources :dis_packagetypes
     resources :dis_pregnancy_categories
     resources :dis_routed_doseform_generics
     resources :dis_routed_generics
     resources :dis_routes
     resources :dis_statuses
     resources :dis_systems
     resources :dis_therapueticgroups
     resources :dis_vaccine_types
     get '/search', to: 'dis_generics#search', as: 'search'
   end
 end
  resources :combination_doses
  resources :combination_contents
  resources :tests
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'
  root 'static_pages#home'

end

app/models/dis_generic_monograph.rb
class DisGenericMonograph < ActiveRecord::Base
end

app/controllers/api/v1/dis_generic_monographs_controller.rb
module Api
  module V1
class DisGenericMonographsController < ApplicationController
  before_action :set_generic_monograph, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  respond_to :json
  # GET /generic_monographs
  # GET /generic_monographs.json
  def index
  # @cd = DisGenericMonograph.all
    c = DisGenericMonograph.paginate(:page => params[:page], :per_page => 10)
    e = c.count
    c = c.as_json
    d = [{"Count" => e}]
    m = {"a" => c ,"b" => d}
    #  n = c.to_a << @m
    respond_with m
  end

  # GET /generic_monographs/1
  # GET /generic_monographs/1.json
  def show
     respond_with DisGenericMonograph.find(params[:id])
  end

  # GET /generic_monographs/new
  def new
    @generic_monograph = DisGenericMonograph.new
  end

  # GET /generic_monographs/1/edit
  def edit
  end

  # POST /generic_monographs
  # POST /generic_monographs.json
  def create
    @generic_monograph = DisGenericMonograph.new(generic_monograph_params)


      if @generic_monograph.save
        flash[:notice] = "Task was successfully created."
         respond_with(@generic_monograph)
       else
         flash[:notice] = "Task was not created."
       end
  end

  # PATCH/PUT /generic_monographs/1
  # PATCH/PUT /generic_monographs/1.json
  def update
    respond_to do |format|
      if @generic_monograph.update(generic_monograph_params)
        format.html { redirect_to @generic_monograph, notice: 'Combination dose was successfully updated.' }
        format.json { render :show, status: :ok, location: @generic_monograph }
      else
        format.html { render :edit }
        format.json { render json: @generic_monograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generic_monographs/1
  # DELETE /generic_monographs/1.json
  def destroy
    @generic_monograph.destroy
    respond_to do |format|
      format.html { redirect_to generic_monographs_url, notice: 'Combination dose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generic_monograph
      @generic_monograph = DisGenericMonograph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generic_monograph_params
      params.require(:generic_monograph).permit(:generic_id, :dose, :contraindication, :precaution, :adverse_effect, :storage, :datasource_id, :status_id)
    end
end
 end
 end

app/controllers/dis_generic_monographs_controller.rb
class DisGenericMonographsController < ApplicationController
  before_action :set_dis_generic_monograph, only: [:show, :edit, :update, :destroy]

  # GET /dis_generic_monographs
  # GET /dis_generic_monographs.json
  def index
    @dis_generic_monographs = DisGenericMonograph.all
  end

  # GET /dis_generic_monographs/1
  # GET /dis_generic_monographs/1.json
  def show
  end

  # GET /dis_generic_monographs/new
  def new
    @dis_generic_monograph = DisGenericMonograph.new
  end

  # GET /dis_generic_monographs/1/edit
  def edit
  end

  # POST /dis_generic_monographs
  # POST /dis_generic_monographs.json
  def create
    @dis_generic_monograph = DisGenericMonograph.new(dis_generic_monograph_params)

    respond_to do |format|
      if @dis_generic_monograph.save
        format.html { redirect_to @dis_generic_monograph, notice: 'Dis generic monograph was successfully created.' }
        format.json { render :show, status: :created, location: @dis_generic_monograph }
      else
        format.html { render :new }
        format.json { render json: @dis_generic_monograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dis_generic_monographs/1
  # PATCH/PUT /dis_generic_monographs/1.json
  def update
    respond_to do |format|
      if @dis_generic_monograph.update(dis_generic_monograph_params)
        format.html { redirect_to @dis_generic_monograph, notice: 'Dis generic monograph was successfully updated.' }
        format.json { render :show, status: :ok, location: @dis_generic_monograph }
      else
        format.html { render :edit }
        format.json { render json: @dis_generic_monograph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dis_generic_monographs/1
  # DELETE /dis_generic_monographs/1.json
  def destroy
    @dis_generic_monograph.destroy
    respond_to do |format|
      format.html { redirect_to dis_generic_monographs_url, notice: 'Dis generic monograph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dis_generic_monograph
      @dis_generic_monograph = DisGenericMonograph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dis_generic_monograph_params
      params.require(:dis_generic_monograph).permit(:generic_id, :dose, :contraindication, :precaution, :adverse_effect, :storage, :datasource_id, :status_id)
    end
end

app/helpers/dis_generic_monographs_helper.rb
module DisGenericMonographsHelper
end

app/views/dis_generic_monographs/_form.html.erb
<%= simple_form_for(@dis_generic_monograph) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :generic_id %>
    <%= f.input :dose %>
    <%= f.input :contraindication %>
    <%= f.input :precaution %>
    <%= f.input :adverse_effect %>
    <%= f.input :storage %>
    <%= f.input :datasource_id %>
    <%= f.input :status_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dis_generic_monographs/edit.html.erb
<h1>Editing Dis Generic Monograph</h1>

<%= render 'form' %>

<%= link_to 'Show', @dis_generic_monograph %> |
<%= link_to 'Back', dis_generic_monographs_path %>

app/views/dis_generic_monographs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dis Generic Monographs</h1>

<table id="example" class="table table-bordered table-hover table-striped datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Generic</th>
      <th>Dose</th>
      <th>Contraindication</th>
      <th>Precaution</th>
      <th>Adverse effect</th>
      <th>Storage</th>
      <th>Datasource</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @dis_generic_monographs.each do |dis_generic_monograph| %>
      <tr>
        <td><%= dis_generic_monograph.generic_id %></td>
        <td><%= dis_generic_monograph.dose %></td>
        <td><%= dis_generic_monograph.contraindication %></td>
        <td><%= dis_generic_monograph.precaution %></td>
        <td><%= dis_generic_monograph.adverse_effect %></td>
        <td><%= dis_generic_monograph.storage %></td>
        <td><%= dis_generic_monograph.datasource_id %></td>
        <td><%= dis_generic_monograph.status_id %></td>
        <td><%= link_to 'Show', dis_generic_monograph %>,<%= link_to 'Edit', edit_dis_generic_monograph_path(dis_generic_monograph) %>,<%= link_to 'Destroy', dis_generic_monograph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dis Generic Monograph', new_dis_generic_monograph_path %>

app/views/dis_generic_monographs/new.html.erb
<h1>New Dis Generic Monograph</h1>

<%= render 'form' %>

<%= link_to 'Back', dis_generic_monographs_path %>

app/views/dis_generic_monographs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Generic:</strong>
  <%= @dis_generic_monograph.generic_id %>
</p>

<p>
  <strong>Dose:</strong>
  <%= @dis_generic_monograph.dose %>
</p>

<p>
  <strong>Contraindication:</strong>
  <%= @dis_generic_monograph.contraindication %>
</p>

<p>
  <strong>Precaution:</strong>
  <%= @dis_generic_monograph.precaution %>
</p>

<p>
  <strong>Adverse effect:</strong>
  <%= @dis_generic_monograph.adverse_effect %>
</p>

<p>
  <strong>Storage:</strong>
  <%= @dis_generic_monograph.storage %>
</p>

<p>
  <strong>Datasource:</strong>
  <%= @dis_generic_monograph.datasource_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dis_generic_monograph.status_id %>
</p>

<%= link_to 'Edit', edit_dis_generic_monograph_path(@dis_generic_monograph) %> |
<%= link_to 'Back', dis_generic_monographs_path %>