config/routes.rb
Rails.application.routes.draw do
  resources :dis_doseunits
  resources :dis_doseform_route_maps
  resources :dis_generic_hepatic_imps
  resources :dis_duplicate_therapies
  resources :dis_doseform_doseunit_links
  resources :dis_dispensable_generics
  resources :dis_vaccine_types
  resources :dis_additive_frequencies
  resources :dis_doseperiods
  resources :dis_doseperiods
  resources :dis_drug_drug_interactions
  resources :dis_routed_doseform_generics
  resources :dis_doseunit_convertions
  resources :dis_generic_alcohol_interactions
  resources :dis_nfi_schedules
  resources :dis_generic_lactations
  resources :dis_generic_monographs
  resources :dis_generic_contraceptive_interactions
  resources :dis_alcohol_interactions
  resources :dis_datasources
  resources :dis_brandnames
  resources :dis_doseforms
  resources :dis_durations
  resources :dis_foodintakes
  resources :dis_generics
  resources :dis_generic_indications
  resources :dis_indiastates
  resources :dis_indications
  resources :dis_ingredients
  resources :dis_manufacturers
  resources :dis_packagetypes
  resources :dis_pregnancy_categories
  resources :dis_routes
  resources :dis_routed_generics
  resources :dis_statuses
  resources :dis_systems
  resources :dis_therapueticgroups
  namespace :api, defaults: {format: 'json'} do
  namespace :v1 do
     resources :combination_doses
     resources :combination_contents
     resources :dis_generics
     resources :dis_additive_frequencies
     resources :dis_alcohol_interactions
     resources :dis_brandnames
     resources :dis_datasources
     resources :dis_dispensable_generics
     resources :dis_doseform_doseunit_links
     resources :dis_doseform_route_maps
     resources :dis_doseforms
     resources :dis_doseperiods
     resources :dis_doseunit_convertions
     resources :dis_doseunits
     resources :dis_drug_drug_interactions
     resources :dis_duplicate_therapies
     resources :dis_durations
     resources :dis_foodintakes
     resources :dis_generic_alcohol_interactions
     resources :dis_generic_contraceptive_interactions
     resources :dis_generic_hepatic_imps
     resources :dis_generic_indications
     resources :dis_generic_lactations
     resources :dis_generic_monographs
     resources :dis_indiastates
     resources :dis_indications
     resources :dis_ingredients
     resources :dis_manufacturers
     resources :dis_nfi_schedules
     resources :dis_packagetypes
     resources :dis_pregnancy_categories
     resources :dis_routed_doseform_generics
     resources :dis_routed_generics
     resources :dis_routes
     resources :dis_statuses
     resources :dis_systems
     resources :dis_therapueticgroups
     resources :dis_vaccine_types
     get '/search', to: 'dis_generics#search', as: 'search'
   end
 end
  resources :combination_doses
  resources :combination_contents
  resources :tests
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/help'
  root 'static_pages#home'

end

app/models/dis_doseunit.rb
class DisDoseunit < ActiveRecord::Base
end

app/controllers/api/v1/dis_doseunits_controller.rb
module Api
  module V1
class DisDoseunitsController < ApplicationController
  before_action :set_doseunit, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  respond_to :json
  # GET /doseunits
  # GET /doseunits.json
  def index
  # @cd = DisDoseunit.all
    a = DisDoseunit.paginate(:page => params[:page], :per_page => 10).order(:id)
    @m = array = []
    a.each do |m|
    # user = User.where(id: m.user_two).last
    h = {}
    h["id"] = m.id
    h["name"] = m.name
    h["abbrev"] = m.abbrev
    h["dosetype_id"] = m.dosetype_id
    h["status_id"] = m.status_id
    # Start - Logic to lookup for status
    if m.status_id
    @DisStatus = DisStatus.where(id:m.status_id).last
    h["status_name"] = @DisStatus.name
    else
    h["status_name"] ="no desc"
    end
      # End - Logic to lookup for status
    array << h
    end
    rowcount = a.count
    a = a.as_json
    d = [{"Count" => rowcount}]
    result = {"raw" => a ,"count" => d , "final" => @m}
    #  n = c.to_a << @m
    respond_with result
  end

  # GET /doseunits/1
  # GET /doseunits/1.json
  def show
     respond_with DisDoseunit.find(params[:id])
  end

  # GET /doseunits/new
  def new
    @doseunit = DisDoseunit.new
  end

  # GET /doseunits/1/edit
  def edit
  end

  # POST /doseunits
  # POST /doseunits.json
  def create
    @doseunit = DisDoseunit.new(doseunit_params)


      if @doseunit.save
        flash[:notice] = "Task was successfully created."
         respond_with(@doseunit)
       else
         flash[:notice] = "Task was not created."
       end
  end

  # PATCH/PUT /doseunits/1
  # PATCH/PUT /doseunits/1.json
  def update
    respond_to do |format|
      if @doseunit.update(doseunit_params)
        format.html { redirect_to @doseunit, notice: 'Combination dose was successfully updated.' }
        format.json { render :show, status: :ok, location: @doseunit }
      else
        format.html { render :edit }
        format.json { render json: @doseunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doseunits/1
  # DELETE /doseunits/1.json
  def destroy
    @doseunit.destroy
    respond_to do |format|
      format.html { redirect_to doseunits_url, notice: 'Combination dose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doseunit
      @doseunit = DisDoseunit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doseunit_params
      params.require(:doseunit).permit(:name, :abbrev, :is_common, :dosetype_id, :status_id)
    end
end
 end
 end

app/controllers/dis_doseunits_controller.rb
class DisDoseunitsController < ApplicationController
  before_action :set_dis_doseunit, only: [:show, :edit, :update, :destroy]

  # GET /dis_doseunits
  # GET /dis_doseunits.json
  def index
    @dis_doseunits = DisDoseunit.all
  end

  # GET /dis_doseunits/1
  # GET /dis_doseunits/1.json
  def show
  end

  # GET /dis_doseunits/new
  def new
    @dis_doseunit = DisDoseunit.new
  end

  # GET /dis_doseunits/1/edit
  def edit
  end

  # POST /dis_doseunits
  # POST /dis_doseunits.json
  def create
    @dis_doseunit = DisDoseunit.new(dis_doseunit_params)

    respond_to do |format|
      if @dis_doseunit.save
        format.html { redirect_to @dis_doseunit, notice: 'Dis doseunit was successfully created.' }
        format.json { render :show, status: :created, location: @dis_doseunit }
      else
        format.html { render :new }
        format.json { render json: @dis_doseunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dis_doseunits/1
  # PATCH/PUT /dis_doseunits/1.json
  def update
    respond_to do |format|
      if @dis_doseunit.update(dis_doseunit_params)
        format.html { redirect_to @dis_doseunit, notice: 'Dis doseunit was successfully updated.' }
        format.json { render :show, status: :ok, location: @dis_doseunit }
      else
        format.html { render :edit }
        format.json { render json: @dis_doseunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dis_doseunits/1
  # DELETE /dis_doseunits/1.json
  def destroy
    @dis_doseunit.destroy
    respond_to do |format|
      format.html { redirect_to dis_doseunits_url, notice: 'Dis doseunit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dis_doseunit
      @dis_doseunit = DisDoseunit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dis_doseunit_params
      params.require(:dis_doseunit).permit(:id, :name, :abbrev, :dosetype_id, :status_id)
    end
end

app/helpers/dis_doseunits_helper.rb
module DisDoseunitsHelper
end

app/views/dis_doseunits/_form.html.erb
<%= simple_form_for(@dis_doseunit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id %>
    <%= f.input :name %>
    <%= f.input :abbrev %>
    <%= f.input :dosetype_id %>
    <%= f.input :status_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dis_doseunits/edit.html.erb
<h1>Editing Dis Doseunit</h1>

<%= render 'form' %>

<%= link_to 'Show', @dis_doseunit %> |
<%= link_to 'Back', dis_doseunits_path %>

app/views/dis_doseunits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dis Doseunits</h1>

<table id="example" class="table table-bordered table-hover table-striped datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Abbrev</th>
      <th>Dosetype</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @dis_doseunits.each do |dis_doseunit| %>
      <tr>
        <td><%= dis_doseunit.id %></td>
        <td><%= dis_doseunit.name %></td>
        <td><%= dis_doseunit.abbrev %></td>
        <td><%= dis_doseunit.dosetype_id %></td>
        <td><%= dis_doseunit.status_id %></td>
        <td><%= link_to 'Show', dis_doseunit %>,<%= link_to 'Edit', edit_dis_doseunit_path(dis_doseunit) %>,<%= link_to 'Destroy', dis_doseunit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dis Doseunit', new_dis_doseunit_path %>

app/views/dis_doseunits/new.html.erb
<h1>New Dis Doseunit</h1>

<%= render 'form' %>

<%= link_to 'Back', dis_doseunits_path %>

app/views/dis_doseunits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @dis_doseunit.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dis_doseunit.name %>
</p>

<p>
  <strong>Abbrev:</strong>
  <%= @dis_doseunit.abbrev %>
</p>

<p>
  <strong>Dosetype:</strong>
  <%= @dis_doseunit.dosetype_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dis_doseunit.status_id %>
</p>

<%= link_to 'Edit', edit_dis_doseunit_path(@dis_doseunit) %> |
<%= link_to 'Back', dis_doseunits_path %>